### ISSUE TITLE
FAQ dropdown arrows 

### ISSUE THREAD

**Issue by Shlucus** [JACHacks/JACHacks-Website#17]
Fix FAQ arrows not appearing:
![image](https://github.com/JACHacks/JACHacks-Website/assets/111912000/7daa376a-d75c-4a9f-8cd9-bbd7bff67c7a)

**Comment by tjklint** [comment]
This looks to be fixed. I will close this issue for now to clean up this tab.

**Comment by tjklint** [comment]
p.s. the "+" rotating to a "x" is actually quite cool, good job!
