### ISSUE TITLE
Register button can be a little too bright on mobile.

### ISSUE THREAD

**Issue by tjklint** [JACHacks/JACHacks-Website#8]
The light of the button when open, even on medium brightness can be quite tough on the eye. Maybe a slight reduction in brightness would be sufficient. 

- [x] Reduce glow brightness
- [x] Make cursor change on hover (currently only does on border)

**Comment by fehe-bo** [comment]
done

**Comment by fehe-bo** [comment]
done

**Comment by Shlucus** [comment]
nice work
